-- MySQL Script generated by MySQL Workbench
-- 06/19/17 17:56:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema veterinaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veterinaria
-- -----------------------------------------------------
USE `veterinaria` ;

-- -----------------------------------------------------
-- Table `veterinaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`cliente` (
  `rut` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `fono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria`.`raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`raza` (
  `nombre` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`mascota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `cliente_rut_FK` VARCHAR(10) NOT NULL,
  `raza_nombre_FK` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente__rut_FK_idx` (`cliente_rut_FK` ASC),
  INDEX `raza_nombre_FK1_idx` (`raza_nombre_FK` ASC),
  CONSTRAINT `cliente__rut_FK`
    FOREIGN KEY (`cliente_rut_FK`)
    REFERENCES `veterinaria`.`cliente` (`rut`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `raza_nombre_FK1`
    FOREIGN KEY (`raza_nombre_FK`)
    REFERENCES `veterinaria`.`raza` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria`.`ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`ficha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NOT NULL,
  `peso` FLOAT NOT NULL,
  `tamaño` INT NOT NULL,
  `mascota_id_FK` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mascota_id_FK1_idx` (`mascota_id_FK` ASC),
  CONSTRAINT `mascota_id_FK1`
    FOREIGN KEY (`mascota_id_FK`)
    REFERENCES `veterinaria`.`mascota` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`veterinario` (
  `rut` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria`.`atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria`.`atencion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_atencion` DATE NOT NULL,
  `diagnostico` VARCHAR(200) NOT NULL,
  `tratamiento` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `observacion` VARCHAR(200) NULL,
  `ficha_id_FK` INT NOT NULL,
  `veterinario_rut_FK` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ficha_id_ficha_FK1_idx` (`ficha_id_FK` ASC),
  INDEX `veterinario_rut_FK1_idx` (`veterinario_rut_FK` ASC),
  CONSTRAINT `ficha_id_FK1`
    FOREIGN KEY (`ficha_id_FK`)
    REFERENCES `veterinaria`.`ficha` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `veterinario_rut_FK1`
    FOREIGN KEY (`veterinario_rut_FK`)
    REFERENCES `veterinaria`.`veterinario` (`rut`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
